import React from 'react';

/**
 * On-screen preview of the compliance record. Actual download is handled
 * by utils/printRecord.js which renders a structured letterhead document
 * in a new window and triggers the print dialog.
 */
export default function ComplianceDocument({ record }) {
  if (!record) return null;
  return (
    <article className="compliance-doc" aria-label="Compliance record preview">
      <header className="compliance-doc__header">
        <div className="compliance-doc__brand">
          <span className="compliance-doc__brand-mark" aria-hidden="true"></span>
          <div>
            <div className="compliance-doc__brand-name">Uplevyl</div>
            <div className="compliance-doc__brand-sub">Manager Compliance Record</div>
          </div>
        </div>
        <div className="compliance-doc__record-id">
          Record ID
          <strong>{record.recordId}</strong>
        </div>
      </header>

      <h3 className="compliance-doc__title">Manager Compliance Record</h3>

      <dl className="compliance-doc__grid">
        <dt>Date generated</dt><dd>{record.timestamp}</dd>
        <dt>Location</dt><dd>{record.location}</dd>
        <dt>Employee ID</dt><dd>{record.employeeId}</dd>
        <dt>Jurisdiction</dt><dd>{record.jurisdiction}</dd>
      </dl>

      <div className="compliance-doc__section">
        <h4>Situation summary</h4>
        <p>{record.situationSummary}</p>
      </div>

      <div className="compliance-doc__section">
        <h4>Actions taken</h4>
        <ul>
          {record.actionsTaken.map((a, i) => (
            <li key={i}>✓ {a}</li>
          ))}
        </ul>
      </div>

      <div className="compliance-doc__section">
        <h4>Authority</h4>
        <p>{record.authority}</p>
      </div>

      <footer className="compliance-doc__footer">
        Attorney-supervised · No PII collected or stored · Confidential<br/>
        Generated by Uplevyl · uplevyl.com
      </footer>
    </article>
  );
}
